### ISSUE TITLE
Problem with latest build

### ISSUE THREAD

**Issue by juliogiraldo** [dondominio/whmcs#13]
Hi there!
With latest build of dondominio module for WHMCS appear the following error when I try to access via Admin 

```
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

For additional assistance, please reference the WHMCS TroubleShooting Guide »

Error: Call to a member function proxy() on null in /var/www/vhosts/corescc.com/panel.corescc.com/includes/dondominio/sdk/src/API.php:148
Stack trace:
#0 /var/www/vhosts/corescc.com/panel.corescc.com/modules/addons/dondominio/lib/Services/API_Service.php(414): Dondominio\API\API->__call('list', Array)
#1 /var/www/vhosts/corescc.com/panel.corescc.com/modules/addons/dondominio/lib/Controllers/Admin/Home_Controller.php(50): WHMCS\Module\Addon\Dondominio\Services\API_Service->getSSLCertificates(1, 1)
#2 /var/www/vhosts/corescc.com/panel.corescc.com/modules/addons/dondominio/lib/Controllers/AdminDispatcher.php(86): WHMCS\Module\Addon\Dondominio\Controllers\Admin\Home_Controller->view_Index()
#3 /var/www/vhosts/corescc.com/panel.corescc.com/modules/addons/dondominio/dondominio.php(153): WHMCS\Module\Addon\Dondominio\Controllers\AdminDispatcher->dispatch('', NULL)
#4 /var/www/vhosts/corescc.com/panel.corescc.com/admin/addonmodules.php(0): dondominio_output(Array)
#5 {main}
```

But If I enter with the parameter "&__c__=dashboard" in URL appear to be working fine.

**Comment by JAndreuSoler** [comment]
Hi, as a first option, we see that the error could be due to the fact that DonDominio SDK in the `includes` folder is not updated, you can check the SDK Version in `src/includes/dondominio/sdk/src/version.json`, if version is not `2.0.7` you can update it quickly by reinstalling the module in the administration section in DonDominio Manager dashboard (`/admin/addonmodules.php?module=dondominio&__c__=dashboard`)
![DonDominioDashboard](https://user-images.githubusercontent.com/46518878/133248128-40d216ca-f2ea-49a0-9183-dbd4747888c8.png)
